INSERT INTO GENEROS (NOMBRE) VALUES('Accion'); INSERT INTO GENEROS (NOMBRE) VALUES('Comedia'); INSERT INTO GENEROS (NOMBRE) VALUES('Drama'); INSERT INTO GENEROS (NOMBRE) VALUES('Fantasia'); INSERT INTO GENEROS (NOMBRE) VALUES('Terror'); 
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Jack Nicholson', 'https://www.purotip.com/wp-content/uploads/2012/04/jack-nicholson-0.jpg'); INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Tom Hanks', 'https://www.purotip.com/wp-content/uploads/2012/04/tomhanks.jpg'); 
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Johnny Depp', 'https://www.purotip.com/wp-content/uploads/2012/04/jhonnydeep.jpg'); 
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Anthony Hopkins', 'https://www.purotip.com/wp-content/uploads/2012/04/anthonyhopkins.jpg'); INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Denzel Washington', 'https://www.purotip.com/wp-content/uploads/2012/04/denzelwashington.jpg'); INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Leonardo Dicaprio', 'https://www.purotip.com/wp-content/uploads/2012/04/leonardo-dicaprio1.jpg'); 
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES("Morgan Freeman", 'https://www.purotip.com/wp-content/uploads/2012/04/morganfreeman.jpg');

INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES("Tom Cruise", 'https://www.purotip.com/wp-content/uploads/2012/04/tomcruise.jpg'); INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES("Brad Pitt", 'https://www.purotip.com/wp-content/uploads/2012/04/bradpitt.jpg'); INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES("Robert De Niro", 'https://www.purotip.com/wp-content/uploads/2012/04/robertdeniro.jpg');



INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test11', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test12', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test13', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test14', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test15', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test16', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test17', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test18', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test19', 1, '2022-01-01'); INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Pelicula Test20', 1, '2022-01-01');
